export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART"
export const DECRESE_ITEM_TO_CART = "DECRESE_ITEM_TO_CART"
export const INCREASE_ITEM_TO_CART = "INCREASE_ITEM_TO_CART"
export const DELETE_ITEM_FROM_CART = "DELETE_ITEM_FROM_CART"
export const CLEAR_ITEM_CART = "CLEAR_ITEM_CART"



