export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS"
export const GET_PROFILE_PENDING = "GET_PROFILE_PENDING"
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL"
export const ADD_PROFILE = "ADD_PROFILE"
export const LOGOUT_PROFILE = "LOGOUT_PROFILE"


